<?php 
$continents_countries_data = array(
        'Asia' => array(
            'countries' => array(
                '中国（Zhōngguó / China）',
                'にほん（Nihon / Japan）',
            )
        ),
        'Europe' => array(
            'countries' => array(
                'Россия（Rossiya / Russia）',
                'Deutschland（Germany）',
                'France（France）',
                'United Kingdom（United Kingdom）',
                'Italia（Italy）',
                'España（Spain）',
                'Portugal（Portugal）',
                'Polska（Poland）',
                'Україна（Ukraina / Ukraine）',
                'Ελλάδα（Elláda / Greece）',
                'Nederland（Netherlands）',
                'België / Belgique / Belgien（Belgium）',
                'Schweiz / Suisse / Svizzera / Svizra（Switzerland）',
                'Sverige（Sweden）',
                'Norge / Noreg（Norway）',
                'Suomi / Finland（Finland）',
                'Österreich（Austria）',
                'Magyarország（Hungary）',
                'Éire（Ireland）',
                'Luxembourg / Luxemburg / Lëtzebuerg（Luxembourg）',
                'Monaco（Monaco）',
                'Andorra（Andorra）',
                'Liechtenstein（Liechtenstein）',
                'Vaticanum / Civitas Vaticana（Vatican City）',
                'San Marino（San Marino）',
                'Malta（Malta）',
                'Eesti（Estonia）',
                'Latvija（Latvia）',
                'Lietuva（Lithuania）',
                'Беларусь（Belarus）',
                'Moldova / Молдова（Moldova）',
                'Hrvatska（Croatia）',
                'Босна и Херцеговина（Bosna i Hercegovina / Bosnia and Herzegovina）',
                'Србија（Srbija / Serbia）',
                'Црна Гора（Crna Gora / Montenegro）',
                'Северна Македонија（Severna Makedonija / North Macedonia）',
                'Шqipëria（Albanija / Albania）',
                'Gibraltar（Gibraltar）',
                'Færøerne（Faroe Islands）',
            )
        ),
        'North America' => array(
            'countries' => array(
                'Canada（Canada）',
                'United States（United States）',
                'México（Mexico）',
                'Guatemala（Guatemala）',
                'Belice（Belize）',
                'El Salvador（El Salvador）',
                'Honduras（Honduras）',
                'Nicaragua（Nicaragua）',
                'Costa Rica（Costa Rica）',
                'Panamá（Panama）',
                'Cuba（Cuba）',
                'Jamaica（Jamaica）',
                'Bahamas（Bahamas）',
                'Haïti（Haiti）',
                'República Dominicana（Dominican Republic）',
                'Antigua y Barbuda（Antigua and Barbuda）',
                'San Cristóbal y Nieves（Saint Kitts and Nevis）',
                'Dominica（Dominica）',
                'Santa Lucía（Saint Lucia）',
                'San Vicente y las Granadinas（Saint Vincent and the Grenadines）',
                'Barbados（Barbados）',
                'Granada（Grenada）',
                'Trinidad y Tobago（Trinidad and Tobago）',
                'Groenlandia / Grønland（Greenland）',
                'Saint',
                'Bermudas（Bermuda）',
                'Turks and Caicos Islands（Turks and Caicos Islands）',
                'Cayman Islands（Cayman Islands）',
                'Puerto Rico（Puerto Rico）',
                'Virgin Islands (EE.UU.)（United States Virgin Islands）',
                'Virgin Islands (Reino Unido)（British Virgin Islands）',
                'Anguilla（Anguilla）',
                'Montserrat（Montserrat）',
                'Guadalupe（Guadeloupe）',
                'Martinica（Martinique）',
                'Curaçao（Curaçao）',
                'Aruba（Aruba）',
            )
        ),
        'South America' => array(
            'countries' => array(
                'Colombia（Colombia）',
                'Venezuela（Venezuela）',
                'Perú（Peru）',
                'Ecuador（Ecuador）',
                'Bolivia（Bolivia）',
                'Paraguay（Paraguay）',
                'Guyana（Guyana）',
                'Suriname（Suriname）',
                'Brasil（Brazil）',
                'Chile（Chile）',
                'Argentina（Argentina）',
                'Uruguay（Uruguay）',
                'Guyane française（French Guiana）',
                'Islas Malvinas（Falkland Islands）',
            )
        ),
        'Africa' => array(
            'countries' => array(
                'مصر（Miṣr / Egypt）',
                'ليبيا（Lībiyā / Libya）',
                'المغرب（al',
                'تونس（Tūnis / Tunisia）',
                'موريتانيا（Mūrītānyā / Mauritania）',
                'مالي（Mālī / Mali）',
                'السنغال（as',
                'الغامبيا（al',
                'الجزائر（al',
                'Burkina Faso（Burkina Faso）',
                'الرأس الأخضر（ar',
                'Guiné',
                'غينيا（Ghinīyā / Guinea）',
                'سيراليون（Sīrāliyūn / Sierra Leone）',
                'ليبريا（Lībriyā / Liberia）',
                'Côte d’Ivoire（Côte d\'Ivoire）',
                'غانا（Ghāna / Ghana）',
                'توجو（Tūjū / Togo）',
                'بينين（Bīnīn / Benin）',
                'النجر（an',
                'نيجيريا（Nījīryā / Nigeria）',
                'كاميرون（Kāmīrūn / Cameroon）',
                'غينيا الاستوائية（Ghinīyā al',
                'São Tomé e Príncipe（São Tomé and Príncipe）',
                'تشاد（Tshād / Chad）',
                'السودان（as',
                'السودان الجنوبي（as',
                'République Centrafricaine（Central African Republic）',
                'ኢትዮጵያ（Ītyōṗṗyā / Ethiopia）',
                'ኤርትራ（Ēritrā / Eritrea）',
                'الصومال（aṣ',
                'جيبوتي（Jībūtī / Djibouti）',
                'كينيا（Kīnyā / Kenya）',
                'أوغندا（Ūghandā / Uganda）',
                'تانزانيا（Tānzānyā / Tanzania）',
                'رواندا（Ruwāndā / Rwanda）',
                'بروندى（Burundī / Burundi）',
                'République Démocratique du Congo（Democratic Republic of the Congo）',
                'République du Congo（Republic of the Congo）',
                'الغابون（al',
                'Zambie（Zambia）',
                'Malawi（Malawi）',
                'Moçambique（Mozambique）',
                'القمر（al',
                'Madagascar（Madagascar）',
                'Seychelles（Seychelles）',
                'Maurice（Mauritius）',
                'Namibie（Namibia）',
                'Botswana（Botswana）',
                'Zimbabwe（Zimbabwe）',
                'Sudáfrica（South Africa）',
                'Eswatini（Eswatini）',
                'Lesotho（Lesotho）',
                'La Réunion（La Réunion）',
                'Sáhara Occidental（Western Sahara）',
                'Santa Helena（Saint Helena）',
            )
        ),
        'Oceania' => array(
            'countries' => array(
                'Australia（Australia）',
                'Papua New Guinea（Papua New Guinea）',
                'Solomon Islands（Solomon Islands）',
                'Aotearoa（New Zealand）',
                'Palau（Palau）',
                'Niue（Niue）',
                'Nauru（Nauru）',
                'Federated States of Micronesia（Federated States of Micronesia）',
                'Marshall Islands（Marshall Islands）',
                'Cook Islands（Cook Islands）',
                'Tuvalu（Tuvalu）',
                'Tonga（Tonga）',
                'Kiribati（Kiribati）',
                'Vanuatu（Vanuatu）',
                'Fiji（Fiji）',
                'Samoa（Samoa）',
                'Norfolk Island（Norfolk Island）',
                'Christmas Island（Christmas Island）',
                'Cocos (Keeling) Islands（Cocos (Keeling) Islands）',
                'Northern Mariana Islands（Northern Mariana Islands）',
                'Guam（Guam）',
                'Tokelau（Tokelau）',
                'Wallis et Futuna（Wallis and Futuna）',
                'Nouvelle',
                'American Samoa（American Samoa）',
                'Polynésie française（French Polynesia）',
                'Pitcairn Islands（Pitcairn Islands）',
            )
        )
    );